d-apache2-openssl:
  ports:
  - 65505:22/tcp
  - 65506:80/tcp
  - 443:443/tcp
  environment:
    DWL_USER_NAME: dwl
    DWL_USER_PASSWD: dwl
    DWL_SSH_ACCESS: 'true'
    DWL_USER_ID: '1000'
    DWL_USER_DNS: dev.davaskweblimited.com
    DWL_SSLKEY_C: EU
    DWL_SSLKEY_ST: France
    DWL_SSLKEY_L: Vannes
    DWL_SSLKEY_O: davask web limited - docker container
    DWL_SSLKEY_CN: davaskweblimited.com
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: dwl=dwlComPrivate
  tty: true
  hostname: dev.davaskweblimited.com
  image: davask/d-apache-openssl2:2.4-u14.04
  volumes:
  - /home/dwl/projects/factory/docker-dev/files:/home/dwl/files
  - /home/dwl/projects/factory/docker-dev/sites-enabled:/etc/apache2/sites-enabled
  - /home/dwl/projects/factory/docker-dev/ssl:/etc/apache2/ssl
  - /home/dwl/projects/factory/docker-dev/lestencrypt:/etc/lestencrypt
  stdin_open: true

d-apache2:
  ports:
  - 65503:22/tcp
  - 65504:80/tcp
  environment:
    DWL_USER_NAME: dwl
    DWL_USER_PASSWD: dwl
    DWL_SSH_ACCESS: 'true'
    DWL_USER_ID: '1000'
  labels:
    io.rancher.container.start_once: 'true'
    io.rancher.scheduler.affinity:host_label: dwl=dwlComPrivate
  tty: true
  hostname: apache2.davaskweblimited.com
  image: davask/d-apache2:2.4-u14.04
  volumes:
  - /home/dwl/projects/factory/docker-dev/files:/home/dwl/files
  - /home/dwl/projects/factory/docker-dev/sites-enabled:/etc/apache2/sites-enabled
  stdin_open: true

d-base:
  ports:
  - 65501:22/tcp
  environment:
    DWL_SSH_ACCESS: 'true'
    DWL_USER_NAME: dwl
    DWL_USER_PASSWD: dwl
    DWL_USER_ID: '1000'
  labels:
    io.rancher.container.start_once: 'true'
    io.rancher.scheduler.affinity:host_label: dwl=dwlComPrivate
  tty: true
  hostname: base.davaskweblimited.com
  image: davask/d-base:u14.04
  volumes:
  - /home/dwl/projects/factory/docker-dev:/home/dwl
  stdin_open: true

d-ubuntu:
  ports:
  - 65500:22/tcp
  environment:
    DWL_SSH_ACCESS: 'true'
    DWL_USER_NAME: dwl
    DWL_USER_PASSWD: dwl
    DWL_USER_ID: '1000'
  labels:
    io.rancher.container.start_once: 'true'
    io.rancher.scheduler.affinity:host_label: dwl=dwlComPrivate
  tty: true
  hostname: ubuntu.davaskweblimited.com
  image: davask/d-ubuntu:14.04
  volumes:
  - /home/dwl/projects/factory/docker-dev:/home/dwl
  stdin_open: true
